

const studentdata = [

    {
        name     :  'Asraful',
        roll     : 1,
        age      : 10,
        class    : 5,
        gender   : 'male',
        location : 'Dhaka',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 7,
        rel      : 90,
    },
    {
        name     :  'Robin',
        roll     : 2,
        age      : 15,
        class    : 3,
        gender   : 'male',
        location : 'Uttora',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Ashik',
        roll     : 3,
        age      : 22,
        class    : 5,
        gender   : 'male',
        location : 'Banani',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Maliha',
        roll     : 4,
        age      : 15,
        class    : 2,
        gender   : 'Female',
        location : 'Dhaka',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Borna',
        roll     : 5,
        age      : 10,
        class    : 2,
        gender   : 'Female',
        location : 'Uttora',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Sahida',
        roll     : 6,
        age      : 15,
        class    : 5,
        gender   : 'Female',
        location : 'Banani',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Firoz',
        roll     : 7,
        age      : 20,
        class    : 5,
        gender   : 'male',
        location : 'Uttora',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Jidan',
        roll     : 8,
        age      : 22,
        class    : 3,
        gender   : 'male',
        location : 'Banani',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Kawsar',
        roll     : 9,
        age      : 10,
        class    : 5,
        gender   : 'male',
        location : 'Dhaka',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Asraful',
        roll     : 10,
        age      : 10,
        class    : 2,
        gender   : 'male',
        location : 'Uttora',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Somrat',
        roll     : 11,
        age      : 15,
        class    : 3,
        gender   : 'male',
        location : 'Dhaka',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Hossain',
        roll     : 12,
        age      : 10,
        class    : 5,
        gender   : 'male',
        location : 'Dhaka',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Mariya',
        roll     : 13,
        age      : 22,
        class    : 3,
        gender   : 'Female',
        location : 'Uttora',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Mahi',
        roll     : 14,
        age      : 15,
        class    : 2,
        gender   : 'Female',
        location : 'Dhaka',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Sumon',
        roll     : 15,
        age      : 25,
        class    : 5,
        gender   : 'male',
        location : 'Banani',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Akas',
        roll     : 16,
        age      : 10,
        class    : 3,
        gender   : 'male',
        location : 'Dhaka',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Mosiur',
        roll     : 17,
        age      : 25,
        class    : 5,
        gender   : 'male',
        location : 'Uttora',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Sakil',
        roll     : 18,
        age      : 10,
        class    : 2,
        gender   : 'male',
        location : 'Dhaka',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Sagor',
        roll     : 19,
        age      : 15,
        class    : 5,
        gender   : 'male',
        location : 'Dhaka',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Bappi',
        roll     : 20,
        age      : 10,
        class    : 5,
        gender   : 'male',
        location : 'Dhaka',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Minhaj',
        roll     : 21,
        age      : 10,
        class    : 5,
        gender   : 'male',
        location : 'Dhaka',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Foysal',
        roll     : 22,
        age      : 10,
        class    : 5,
        gender   : 'male',
        location : 'Dhaka',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Nasir',
        roll     : 23,
        age      : 15,
        class    : 5,
        gender   : 'male',
        location : 'Uttora',
        english  : 50,
        bangla   : 86,
        math     : 57,
        ss       : 56,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Irfan',
        roll     : 24,
        age      : 10,
        class    : 5,
        gender   : 'male',
        location : 'Dhaka',
        english  : 60,
        bangla   : 86,
        math     : 87,
        ss       : 76,
        science  : 87,
        rel      : 70,
    },
    {
        name     :  'Akhi',
        roll     : 25,
        age      : 10,
        class    : 3,
        gender   : 'Female',
        location : 'Banani',
        english  : 50,
        bangla   : 86,
        math     : 77,
        ss       : 58,
        science  : 87,
        rel      : 90,
    },
    {
        name     :  'Bristi',
        roll     : 26,
        age      : 22,
        class    : 5,
        gender   : 'Female',
        location : 'Dhaka',
        english  : 50,
        bangla   : 86,
        math     : 78,
        ss       : 56,
        science  : 86,
        rel      : 90,
    },
    {
        name     :  'Sharmin',
        roll     : 27,
        age      : 10,
        class    : 2,
        gender   : 'Female',
        location : 'Dhaka',
        english  : 59,
        bangla   : 86,
        math     : 75,
        ss       : 58,
        science  : 81,
        rel      : 80,
    },
    {
        name     :  'Sakib',
        roll     : 28,
        age      : 10,
        class    : 5,
        gender   : 'male',
        location : 'Dhaka',
        english  : 70,
        bangla   : 76,
        math     : 79,
        ss       : 56,
        science  : 88,
        rel      : 95,
    },
    {
        name     :  'Milon',
        roll     : 29,
        age      : 15,
        class    : 5,
        gender   : 'male',
        location : 'Uttora',
        english  : 60,
        bangla   : 85,
        math     : 76,
        ss       : 56,
        science  : 87,
        rel      : 95,
    },
    {
        name     :  'Imran',
        roll     : 30,
        age      : 10,
        class    : 3,
        gender   : 'male',
        location : 'Dhaka',
        english  : 40,
        bangla   : 86,
        math     : 47,
        ss       : 76,
        science  : 68,
        rel      : 39,
    }





];


let data = JSON.stringify(studentdata);
console.log(data);
localStorage.setItem('result', data);



